on:
  push:
    branches:
      - main
name: action
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        node: [18]
    steps:
      # Set secret as environment variable
      - name: Set secret as environment variable
        run: echo "TEST_ENV=${{ secrets.TEST_ENV }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          TEST_ENV: '$TEST_ENV' # Use secret as environment variable
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
